# **Step 1 Import Pandas**
Import pandas

In [1]:
import pandas as pd

# **Step 2 Upload excel file to Google colab**
Uploading the file to google colab for processing

In [5]:
from google.colab import files
uploaded = files.upload()

Saving Canadian Importers Database Excel File Template.xlsx to Canadian Importers Database Excel File Template.xlsx
Saving MajorImportersByHS6ByCountry2012.xlsx to MajorImportersByHS6ByCountry2012.xlsx
Saving MajorImportersbyHS6byCountry2013.xlsx to MajorImportersbyHS6byCountry2013.xlsx
Saving MajorImportersbyHS6bycountry2014.xlsx to MajorImportersbyHS6bycountry2014.xlsx
Saving MajorImportersbyHS6byCountry2015.xlsx to MajorImportersbyHS6byCountry2015.xlsx
Saving MajorImportersbyHS6byCountry2016.xlsx to MajorImportersbyHS6byCountry2016.xlsx
Saving MajorImportersbyHS6byCountry2017.xlsx to MajorImportersbyHS6byCountry2017.xlsx
Saving MajorImportersbyHS6byCountry2018.xlsx to MajorImportersbyHS6byCountry2018.xlsx
Saving MajorImportersbyHS6byCountry2019.xlsx to MajorImportersbyHS6byCountry2019.xlsx

In [6]:
!ls #check directory

'Canadian Importers Database Excel File Template.xlsx'
 MajorImportersByHS6ByCountry2012.xlsx
 MajorImportersbyHS6byCountry2013.xlsx
 MajorImportersbyHS6bycountry2014.xlsx
 MajorImportersbyHS6byCountry2015.xlsx
 MajorImportersbyHS6byCountry2016.xlsx
 MajorImportersbyHS6byCountry2017.xlsx
 MajorImportersbyHS6byCountry2018.xlsx
 MajorImportersbyHS6byCountry2019.xlsx
 sample_data

# **Step 3 Read excel sheets to data frames**
Read the excel worksheets into two different data frames for data join

In [9]:
dfmaster_desc=pd.read_excel('Canadian Importers Database Excel File Template.xlsx',sheet_name='Sheet3')
df_2020=pd.read_excel('Canadian Importers Database Excel File Template.xlsx',sheet_name='Sheet2')
df_2019=pd.read_excel('MajorImportersbyHS6byCountry2019.xlsx',sheet_name='MajorImportersbyHS6byCountry201')
df_2018=pd.read_excel('MajorImportersbyHS6byCountry2018.xlsx',sheet_name='ImportersbyHS6byCountry2018')
df_2017=pd.read_excel('MajorImportersbyHS6byCountry2017.xlsx',sheet_name='MajorImportersbyHS6byCountry201')
df_2016=pd.read_excel('MajorImportersbyHS6byCountry2016.xlsx',sheet_name='MajorImportersbyHS6byCountry201')
df_2015=pd.read_excel('MajorImportersbyHS6byCountry2015.xlsx',sheet_name='MajorImportersbyHS6byCountry201')
df_2014=pd.read_excel('MajorImportersbyHS6bycountry2014.xlsx',sheet_name='MajorImporterbyHS6bycountry2014')
df_2013=pd.read_excel('MajorImportersbyHS6byCountry2013.xlsx',sheet_name='MajorImportersbyHS6byCountry201')
df_2012=pd.read_excel('MajorImportersByHS6ByCountry2012.xlsx',sheet_name='MajorImporterByHS6ByCountry2012')

In [10]:
dfmaster_desc.head() #show dfmaster_desc data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure"
1,10129,"Horses, live, other than pure-bred breeding","Chevaux vivants, autres que reproducteurs de r..."
2,10130,"Asses, live",Ânes vivants
3,10190,"Mules and hinnies, live",Mulets et bardots vivants
4,10221,"Cattle, live, pure-bred breeding","Bovins domestiques, vivants, reproducteurs de ..."

In [11]:
df_2020.head() #show df_2020 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,WORKWIZE ENTERPRISES,United States,États-Unis,Alberta,Alberta,Acme,T0M 0A0,2020
1,10121,2679591 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Almonte,K0A 1A0,2020
2,10121,BADDECK VETERINARY CLINIC LIMITED,United States,États-Unis,Nova Scotia,Nouvelle-Écosse,Baddeck,B0E 1B0,2020
3,10121,605512 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Bolton,L7E 3R4,2020
4,10121,DEEMAR INVESTMENTS LIMITED,United States,États-Unis,Ontario,Ontario,Caledon,L7C 1Z1,2020

In [12]:
df_2019.head() #show df_2019 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,STONEBRIDGE FARM,United States,États-Unis,Ontario,Ontario,Arva,N0M 1C0,2019
1,10121,HILLCREST LAND & LIVESTOCK LTD,United States,États-Unis,Saskatchewan,Saskatchewan,Beechy,S0L 0C0,2019
2,10121,SILVER HILLS VENTURES LTD.,United States,États-Unis,Manitoba,Manitoba,Boissevain,R0K 0E0,2019
3,10121,605512 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Bolton,L7E 3R4,2019
4,10121,BEAR STABLES LTD.,United States,États-Unis,Alberta,Alberta,Bonnyville,T9N 2G8,2019

In [13]:
df_2018.head() #show df_2018 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,L. POOL HAY SALES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 0A1,2018
1,10121,DELEEUW FARMS LTD.,United States,États-Unis,Alberta,Alberta,Athabasca,T9S 2B1,2018
2,10121,K & J BRIDGEMAN FARMS LTD.,United States,États-Unis,Manitoba,Manitoba,Binscarth,R0J 0G0,2018
3,10121,SILVER HILLS VENTURES LTD.,United States,États-Unis,Manitoba,Manitoba,Boissevain,R0K 0E0,2018
4,10121,NOURISHSWEATSOUL INC.,United States,États-Unis,Alberta,Alberta,Calgary,T2S 0K8,2018

In [14]:
df_2017.head() #show df_2017 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,SANDY RIDGE STALLION STATION,United States,États-Unis,Alberta,Alberta,Bassano,T0J 0B0,2017.0
1,10121,MARIT STABLES LTD,United States,États-Unis,British Columbia,Colombie-Britannique,Cochrane,T4C 0V4,2017.0
2,10121,WINDHORSE FARM,United States,États-Unis,British Columbia,Colombie-Britannique,Coldstream,V1B 3H3,2017.0
3,10121,COLEMAN RANCH,United States,États-Unis,Alberta,Alberta,Didsbury,T0M 0W0,2017.0
4,10121,RIVERLANE RANCH,United States,États-Unis,Alberta,Alberta,Edmonton,T6S 1C4,2017.0

In [15]:
df_2016.head() #show df_2016 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,HIGHLAND VALLEY STABLES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 1N6,2016
1,10121,HOERDT'S HOT SHOT SERVICE LTD.,United States,États-Unis,Alberta,Alberta,Beaumont,T4X 1H9,2016
2,10121,WORLD WIDE CUSTOMS BROKERS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T3N 0A1,2016
3,10121,BAR TT RANCH,United States,États-Unis,Alberta,Alberta,Calgary,T2T 3J1,2016
4,10121,COLEMAN RANCH,United States,États-Unis,Alberta,Alberta,Didsbury,T0M 0W0,2016

In [16]:
df_2015.head() #show df_2015 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,BK QUARTER HORSES,United States,États-Unis,Saskatchewan,Saskatchewan,Abbey,S0N 0A0,2015
1,10121,STRIDE AWAY ACRES,United States,États-Unis,British Columbia,Colombie-Britannique,Armstrong,V0E 1B4,2015
2,10121,CHINOOK VALLEY INC,United States,États-Unis,Alberta,Alberta,Calgary,T2P 3S8,2015
3,10121,CAROUSEL STABLES CORP.,United States,États-Unis,Alberta,Alberta,Calgary,T3R 1G1,2015
4,10121,COLE INTERNATIONAL INC.,United States,États-Unis,Alberta,Alberta,Calgary,T1Y 6X2,2015

In [17]:
df_2014.head() #show df_2014 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,CASTLEROCK CLYDESDALES INC.,United States,États-Unis,Alberta,Alberta,Airdrie,T4B 2A3,2014
1,10121,STRIDE AWAY ACRES,United States,États-Unis,British Columbia,Colombie-Britannique,Armstrong,V0E 1B4,2014
2,10121,RUNAWAY RANCH,United States,États-Unis,Alberta,Alberta,Bentley,T0C 0J0,2014
3,10121,HORSE RIVER VENTURES LIMITED,United States,États-Unis,Alberta,Alberta,Calgary,T2J 1R8,2014
4,10121,DAVE AND BRENDA BATTY CUTTING HORSES,United States,États-Unis,British Columbia,Colombie-Britannique,Coldstream,V1B 3C4,2014

In [18]:
df_2013.head() #show df_2013 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,BRADNER HILL FARMS,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 1K6,2013
1,10121,1554977 ALBERTA LTD.,United States,États-Unis,Alberta,Alberta,Cochrane,T4C 1A5,2013
2,10121,MACKENZIE QUARTER HORSES,United States,États-Unis,Manitoba,Manitoba,Dugald,R0E 0K0,2013
3,10121,BETKAL GROUP,United States,États-Unis,Alberta,Alberta,Edson,T7E 1T8,2013
4,10121,INTERNATIONAL HORSE TRANSPORT LIMITED,United States,États-Unis,Ontario,Ontario,Inglewood,L7C 2E2,2013

In [19]:
df_2012.head() #show df_2012 data

,HS6-SH6,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,JACKSON PLACE INC,United States,États-Unis,Alberta,Alberta,Ardrossan,T8E 2H5,2012
1,10121,D. WEINBERGER HOLDINGS LTD.,United States,États-Unis,Alberta,Alberta,Calgary,T3G 5T4,2012
2,10121,WORLD WIDE CUSTOMS BROKERS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T2P 2M6,2012
3,10121,JACKSON AGRI-BUSINESS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T2P 2G7,2012
4,10121,PRESCOTT FARMS,United States,États-Unis,British Columbia,Colombie-Britannique,Courtenay,V9N 2R6,2012

# **Step 4 Merge the master data frame and yearly data based on Key column**
From the data we can see that "HS6-SH6" is the key column. Both the data frames are merged in this step using the key column.

In [20]:
mergeddf2020= pd.merge(
    dfmaster_desc,
    df_2020,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [21]:
mergeddf2019= pd.merge(
    dfmaster_desc,
    df_2019,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [22]:
mergeddf2018= pd.merge(
    dfmaster_desc,
    df_2018,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [23]:
mergeddf2017= pd.merge(
    dfmaster_desc,
    df_2017,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [24]:
mergeddf2016= pd.merge(
    dfmaster_desc,
    df_2016,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [25]:
mergeddf2015= pd.merge(
    dfmaster_desc,
    df_2015,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [26]:
mergeddf2014= pd.merge(
    dfmaster_desc,
    df_2014,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [27]:
mergeddf2013= pd.merge(
    dfmaster_desc,
    df_2013,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [28]:
mergeddf2012= pd.merge(
    dfmaster_desc,
    df_2012,
    how="inner",
    on="HS6-SH6",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    copy=True,
    indicator=False,
    validate=None,
)

In [29]:
mergeddf2020.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WORKWIZE ENTERPRISES,United States,États-Unis,Alberta,Alberta,Acme,T0M 0A0,2020
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",2679591 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Almonte,K0A 1A0,2020
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BADDECK VETERINARY CLINIC LIMITED,United States,États-Unis,Nova Scotia,Nouvelle-Écosse,Baddeck,B0E 1B0,2020
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",605512 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Bolton,L7E 3R4,2020
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DEEMAR INVESTMENTS LIMITED,United States,États-Unis,Ontario,Ontario,Caledon,L7C 1Z1,2020

In [30]:
mergeddf2019.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",STONEBRIDGE FARM,United States,États-Unis,Ontario,Ontario,Arva,N0M 1C0,2019
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HILLCREST LAND & LIVESTOCK LTD,United States,États-Unis,Saskatchewan,Saskatchewan,Beechy,S0L 0C0,2019
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",SILVER HILLS VENTURES LTD.,United States,États-Unis,Manitoba,Manitoba,Boissevain,R0K 0E0,2019
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",605512 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Bolton,L7E 3R4,2019
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BEAR STABLES LTD.,United States,États-Unis,Alberta,Alberta,Bonnyville,T9N 2G8,2019

In [31]:
mergeddf2018.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",L. POOL HAY SALES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 0A1,2018
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DELEEUW FARMS LTD.,United States,États-Unis,Alberta,Alberta,Athabasca,T9S 2B1,2018
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",K & J BRIDGEMAN FARMS LTD.,United States,États-Unis,Manitoba,Manitoba,Binscarth,R0J 0G0,2018
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",SILVER HILLS VENTURES LTD.,United States,États-Unis,Manitoba,Manitoba,Boissevain,R0K 0E0,2018
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",NOURISHSWEATSOUL INC.,United States,États-Unis,Alberta,Alberta,Calgary,T2S 0K8,2018

In [32]:
mergeddf2017.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",SANDY RIDGE STALLION STATION,United States,États-Unis,Alberta,Alberta,Bassano,T0J 0B0,2017.0
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",MARIT STABLES LTD,United States,États-Unis,British Columbia,Colombie-Britannique,Cochrane,T4C 0V4,2017.0
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WINDHORSE FARM,United States,États-Unis,British Columbia,Colombie-Britannique,Coldstream,V1B 3H3,2017.0
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",COLEMAN RANCH,United States,États-Unis,Alberta,Alberta,Didsbury,T0M 0W0,2017.0
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",RIVERLANE RANCH,United States,États-Unis,Alberta,Alberta,Edmonton,T6S 1C4,2017.0

In [33]:
mergeddf2016.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HIGHLAND VALLEY STABLES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 1N6,2016
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HOERDT'S HOT SHOT SERVICE LTD.,United States,États-Unis,Alberta,Alberta,Beaumont,T4X 1H9,2016
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WORLD WIDE CUSTOMS BROKERS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T3N 0A1,2016
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BAR TT RANCH,United States,États-Unis,Alberta,Alberta,Calgary,T2T 3J1,2016
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",COLEMAN RANCH,United States,États-Unis,Alberta,Alberta,Didsbury,T0M 0W0,2016

In [34]:
mergeddf2015.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BK QUARTER HORSES,United States,États-Unis,Saskatchewan,Saskatchewan,Abbey,S0N 0A0,2015
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",STRIDE AWAY ACRES,United States,États-Unis,British Columbia,Colombie-Britannique,Armstrong,V0E 1B4,2015
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",CHINOOK VALLEY INC,United States,États-Unis,Alberta,Alberta,Calgary,T2P 3S8,2015
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",CAROUSEL STABLES CORP.,United States,États-Unis,Alberta,Alberta,Calgary,T3R 1G1,2015
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",COLE INTERNATIONAL INC.,United States,États-Unis,Alberta,Alberta,Calgary,T1Y 6X2,2015

In [35]:
mergeddf2014.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",CASTLEROCK CLYDESDALES INC.,United States,États-Unis,Alberta,Alberta,Airdrie,T4B 2A3,2014
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",STRIDE AWAY ACRES,United States,États-Unis,British Columbia,Colombie-Britannique,Armstrong,V0E 1B4,2014
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",RUNAWAY RANCH,United States,États-Unis,Alberta,Alberta,Bentley,T0C 0J0,2014
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HORSE RIVER VENTURES LIMITED,United States,États-Unis,Alberta,Alberta,Calgary,T2J 1R8,2014
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DAVE AND BRENDA BATTY CUTTING HORSES,United States,États-Unis,British Columbia,Colombie-Britannique,Coldstream,V1B 3C4,2014

In [36]:
mergeddf2013.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BRADNER HILL FARMS,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 1K6,2013
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",1554977 ALBERTA LTD.,United States,États-Unis,Alberta,Alberta,Cochrane,T4C 1A5,2013
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",MACKENZIE QUARTER HORSES,United States,États-Unis,Manitoba,Manitoba,Dugald,R0E 0K0,2013
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BETKAL GROUP,United States,États-Unis,Alberta,Alberta,Edson,T7E 1T8,2013
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",INTERNATIONAL HORSE TRANSPORT LIMITED,United States,États-Unis,Ontario,Ontario,Inglewood,L7C 2E2,2013

In [37]:
mergeddf2012.head() #show merged data

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",JACKSON PLACE INC,United States,États-Unis,Alberta,Alberta,Ardrossan,T8E 2H5,2012
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",D. WEINBERGER HOLDINGS LTD.,United States,États-Unis,Alberta,Alberta,Calgary,T3G 5T4,2012
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WORLD WIDE CUSTOMS BROKERS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T2P 2M6,2012
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",JACKSON AGRI-BUSINESS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T2P 2G7,2012
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",PRESCOTT FARMS,United States,États-Unis,British Columbia,Colombie-Britannique,Courtenay,V9N 2R6,2012

In [59]:
df_final_data1 = pd.concat([mergeddf2020,mergeddf2019])
df_final_data2 = pd.concat([mergeddf2018,mergeddf2017])
df_final_data3 = pd.concat([mergeddf2016,mergeddf2015])
df_final_data4 = pd.concat([mergeddf2014,mergeddf2013,mergeddf2012])

In [52]:
df_final_data1.head()

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WORKWIZE ENTERPRISES,United States,États-Unis,Alberta,Alberta,Acme,T0M 0A0,2020.0
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",2679591 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Almonte,K0A 1A0,2020.0
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BADDECK VETERINARY CLINIC LIMITED,United States,États-Unis,Nova Scotia,Nouvelle-Écosse,Baddeck,B0E 1B0,2020.0
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",605512 ONTARIO LIMITED,United States,États-Unis,Ontario,Ontario,Bolton,L7E 3R4,2020.0
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DEEMAR INVESTMENTS LIMITED,United States,États-Unis,Ontario,Ontario,Caledon,L7C 1Z1,2020.0

In [60]:
df_final_data2.head()

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",L. POOL HAY SALES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 0A1,2018.0
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DELEEUW FARMS LTD.,United States,États-Unis,Alberta,Alberta,Athabasca,T9S 2B1,2018.0
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",K & J BRIDGEMAN FARMS LTD.,United States,États-Unis,Manitoba,Manitoba,Binscarth,R0J 0G0,2018.0
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",SILVER HILLS VENTURES LTD.,United States,États-Unis,Manitoba,Manitoba,Boissevain,R0K 0E0,2018.0
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",NOURISHSWEATSOUL INC.,United States,États-Unis,Alberta,Alberta,Calgary,T2S 0K8,2018.0

In [63]:
df_final_data3.head()

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HIGHLAND VALLEY STABLES LTD.,United States,États-Unis,British Columbia,Colombie-Britannique,Abbotsford,V4X 1N6,2016
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HOERDT'S HOT SHOT SERVICE LTD.,United States,États-Unis,Alberta,Alberta,Beaumont,T4X 1H9,2016
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",WORLD WIDE CUSTOMS BROKERS LTD,United States,États-Unis,Alberta,Alberta,Calgary,T3N 0A1,2016
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",BAR TT RANCH,United States,États-Unis,Alberta,Alberta,Calgary,T2T 3J1,2016
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",COLEMAN RANCH,United States,États-Unis,Alberta,Alberta,Didsbury,T0M 0W0,2016

In [62]:
df_final_data4.head()

,HS6-SH6,DESCRIPTION_ENG,DESCRIPTION_FRA,COMPANY-ENTREPRISE,COUNTRY,PAYS,PROVINCE_ENG,PROVINCE_FRA,CITY-VILLE,POSTAL_CODE-CODE_POSTAL,DATA_YEAR-ANNÉE_DES_DONNÉES
0,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",CASTLEROCK CLYDESDALES INC.,United States,États-Unis,Alberta,Alberta,Airdrie,T4B 2A3,2014
1,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",STRIDE AWAY ACRES,United States,États-Unis,British Columbia,Colombie-Britannique,Armstrong,V0E 1B4,2014
2,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",RUNAWAY RANCH,United States,États-Unis,Alberta,Alberta,Bentley,T0C 0J0,2014
3,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",HORSE RIVER VENTURES LIMITED,United States,États-Unis,Alberta,Alberta,Calgary,T2J 1R8,2014
4,10121,"Horses, live, pure-bred breeding","Chevaux vivants, reproducteurs de race pure",DAVE AND BRENDA BATTY CUTTING HORSES,United States,États-Unis,British Columbia,Colombie-Britannique,Coldstream,V1B 3C4,2014

In [64]:
df_final_merged_data1=df_final_data1[['HS6-SH6','DESCRIPTION_ENG','COMPANY-ENTREPRISE','COUNTRY','PROVINCE_ENG','CITY-VILLE','POSTAL_CODE-CODE_POSTAL','DATA_YEAR-ANNÉE_DES_DONNÉES']]
df_final_merged_data2=df_final_data2[['HS6-SH6','DESCRIPTION_ENG','COMPANY-ENTREPRISE','COUNTRY','PROVINCE_ENG','CITY-VILLE','POSTAL_CODE-CODE_POSTAL','DATA_YEAR-ANNÉE_DES_DONNÉES']]
df_final_merged_data3=df_final_data3[['HS6-SH6','DESCRIPTION_ENG','COMPANY-ENTREPRISE','COUNTRY','PROVINCE_ENG','CITY-VILLE','POSTAL_CODE-CODE_POSTAL','DATA_YEAR-ANNÉE_DES_DONNÉES']]
df_final_merged_data4=df_final_data4[['HS6-SH6','DESCRIPTION_ENG','COMPANY-ENTREPRISE','COUNTRY','PROVINCE_ENG','CITY-VILLE','POSTAL_CODE-CODE_POSTAL','DATA_YEAR-ANNÉE_DES_DONNÉES']]

# **Step 5 Write merged data to a new excel file**
Using to_excel function to write merged data to new excel file

In [65]:
df_final_merged_data1.to_excel("Merged_data_2020_2019.xlsx")

In [66]:
df_final_merged_data2.to_excel("Merged_data_2018_2017.xlsx")

In [67]:
df_final_merged_data2.to_excel("Merged_data_2016_2015.xlsx")

In [68]:
df_final_merged_data2.to_excel("Merged_data_2014_2012.xlsx")

In [69]:
!ls #check directory

'Canadian Importers Database Excel File Template.xlsx'
 MajorImportersByHS6ByCountry2012.xlsx
 MajorImportersbyHS6byCountry2013.xlsx
 MajorImportersbyHS6bycountry2014.xlsx
 MajorImportersbyHS6byCountry2015.xlsx
 MajorImportersbyHS6byCountry2016.xlsx
 MajorImportersbyHS6byCountry2017.xlsx
 MajorImportersbyHS6byCountry2018.xlsx
 MajorImportersbyHS6byCountry2019.xlsx
 Merged_data_2014_2012.xlsx
 Merged_data_2016_2015.xlsx
 Merged_data_2018_2017.xlsx
 Merged_data_2020_2019.xlsx
 sample_data

# **Step 6 Download the merged data file for Visualizations**
We are using download functionality to download the created excel file

In [71]:
from google.colab import files
files.download("Merged_data_2014_2012.xlsx")

In [72]:
from google.colab import files
files.download("Merged_data_2016_2015.xlsx")

In [73]:
from google.colab import files
files.download("Merged_data_2018_2017.xlsx")

In [74]:
from google.colab import files
files.download("Merged_data_2020_2019.xlsx")